version: 2
jobs:
  build:
    docker:
      - image: fernfernfern/demo:v2
    steps:
      - checkout
      - run: nginx
      - run: nginx -v
      - run: curl localhost:80 | grep "Thank you for using nginx"
      - run: ls -R ../circleci-dockerfiles
